### ISSUE TITLE
<select> box broken in Chrome 53

### ISSUE THREAD

**Issue by gstroup** [PredixDev/px-forms-design#3]
Newest version of Chrome has made the display of the dropdowns ugly.  Look at the bottom of this page:

https://predixdev.github.io/px-forms-design/

![screen shot 2016-09-22 at 2 46 42 pm](https://cloud.githubusercontent.com/assets/431334/18767351/7087d500-80d3-11e6-8179-acdedddf99e8.png)

**Comment by gstroup** [comment]
looks like it's fixed in the latest version.  closing.

**Comment by mdwragg** [comment]
Hey @gstroup - I saw this in Chrome 54 and made this fix for it: f1b2db8231c22575b78bd48f65c91674fd6a62f9

No idea why it the same fix didn't solve things in 53 though!?!?!

http://i.imgur.com/Q3cUg29.gif

**Comment by gstroup** [comment]
No worries, I think it was my dumb mistake!  (I was using an old version.)

Also found that the problem is visible in the new polymer seed app, since we're using an old version of this component.

**Comment by gstroup** [comment]
or maybe the github pages branch needs to be updated too?  Not sure.
